name: "Energy Planner"
version: "1.1.0"
slug: "energy_planner"
description: "Plan when your devices should be switched on or off based on electricity price"
url: "https://github.com/patrsc/energy-planner"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
boot: auto
init: false
map:
  - type: homeassistant_config
    read_only: False
    path: /config
options: {}
schema: {}
ingress: true
panel_icon: mdi:home-lightning-bolt-outline
panel_admin: false
